# Site wide configuration

title: "iecs' Site"
description: "This is a description of my awesome site."
logo: logo.jpg
teaser: 
locale: en
url:
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

#pinglun


# Site owner
owner:
  name: iecs
  email: mfzh502045076@gmail.com
  twitter: iecs
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: logo.jpg # 160x160 px image for author byline
  disqus-shortname: iecs


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
